import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  Alert,
  SafeAreaView,
  StatusBar,
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Import the actual passwords array (generated by the PowerShell script)
const passwords = require('../../assets/passwords.json');

export default function UnlockScreen({ onUnlock }: { onUnlock: () => void }) {
  const [input, setInput] = useState('');
  const [challengeIndex, setChallengeIndex] = useState<number | null>(null);
  const [debugTapCount, setDebugTapCount] = useState(0);

  // Pick a random index once when the screen loads
  useEffect(() => {
    const randomIndex = Math.floor(Math.random() * 300) + 1; // 1‑300
    setChallengeIndex(randomIndex);
  }, []);

  const handleSubmit = async () => {
    if (challengeIndex === null) return;

    const correctPassword = passwords[challengeIndex - 1];

    if (input === correctPassword) {
      await AsyncStorage.setItem('isUnlocked', 'true');
      onUnlock();
    } else {
      Alert.alert('Wrong Password', `Please enter the correct password for p${challengeIndex}`);
      setInput('');
    }
  };

  // Debug: triple‑tap the lock icon to reset lock (for testing only)
  const handleLockPress = async () => {
    const newCount = debugTapCount + 1;
    setDebugTapCount(newCount);
    if (newCount >= 3) {
      await AsyncStorage.removeItem('isUnlocked');
      Alert.alert('Debug', 'Lock status reset. Restart the app to see the unlock screen again.');
      setDebugTapCount(0);
    }
  };

  if (challengeIndex === null) {
    return null; // or a loading spinner
  }

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor="#2D4059" />

      {/* Main content card */}
      <View style={styles.card}>
        {/* Lock icon with triple‑tap debug */}
        <TouchableOpacity onPress={handleLockPress} activeOpacity={0.7}>
          <Text style={styles.lockIcon}>🔒</Text>
        </TouchableOpacity>

        <Text style={styles.title}>App Locked</Text>
        <Text style={styles.instruction}>Enter password to unlock</Text>

        <TextInput
          style={styles.input}
          value={input}
          onChangeText={setInput}
          placeholder={`p${challengeIndex}`}
          placeholderTextColor="#aaa"
          autoCapitalize="none"
          autoCorrect={false}
          secureTextEntry
        />

        <TouchableOpacity style={styles.button} onPress={handleSubmit}>
          <Text style={styles.buttonText}>Unlock</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#2D4059', // dark blue‑grey background
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  card: {
    backgroundColor: '#FEF9E7', // soft off‑white
    borderRadius: 30,
    padding: 30,
    alignItems: 'center',
    width: '100%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
  },
  lockIcon: {
    fontSize: 80,
    marginBottom: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: '600',
    color: '#2D4059',
    marginBottom: 8,
  },
  instruction: {
    fontSize: 16,
    color: '#5C6B7E',
    marginBottom: 30,
    textAlign: 'center',
  },
  input: {
    width: '100%',
    height: 55,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 15,
    paddingHorizontal: 20,
    fontSize: 18,
    backgroundColor: '#fff',
    marginBottom: 25,
    color: '#333',
  },
  button: {
    backgroundColor: '#FF9A8B',
    paddingHorizontal: 50,
    paddingVertical: 16,
    borderRadius: 30,
    elevation: 3,
    shadowColor: '#FF9A8B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
});